backend:
  name: git-gateway
  branch: master


media_folder: "static"
public_folder: "/"

collections:
  - label: "Posts"
    name: "posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Author", name: "author", widget: "hidden", default: "Olly Bee"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}